09.django/d0517/stuPjt/home/urls.py
from django.urls import path,include
from . import views

app_name=''
urlpatterns = [
    path('',views.index,name='index')
]

09.django/d0517/stuPjt/stuPjt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/',include('students.urls')),
    path('',include('home.urls')),
]

09.django/d0517/stuPjt/students/urls.py
from django.urls import path,include
from . import views

app_name='students'
urlpatterns = [
    path('stuWrite/',views.stuWrite,name='stuWrite'), # 학생등록
    path('stuList/',views.stuList,name='stuList'),    # 학생전체리스트
    # 간단url : 데이터추가
    path('<str:name>/<str:major>/stuView/',views.stuView,name='stuView'),    # 학생상세
    
    
    # path('stuWriteOk/',views.stuWriteOk,name='stuWriteOk'),
]

09.django/d0517/stuPjt/students/models.py
from django.db import models

class Student(models.Model):
    s_name = models.CharField(max_length=100)
    s_major = models.CharField(max_length=100)
    s_age = models.IntegerField(default=0)
    s_grade = models.IntegerField(default=0)
    s_gender = models.CharField(max_length=30)
    
    def __str__(self):
        return self.s_name

09.django/d0517/stuPjt/home/views.py
from django.shortcuts import render

# 메인페이지
def index(request):
    return render(request,'index.html')

09.django/d0517/stuPjt/students/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from students.models import Student

# 학생등록페이지
def stuWrite(request):
    # request.method확인으로 함수사용
    if request.method == 'GET':
        return render(request,'stuWrite.html')
    else:
        # form데이터 - POST
        name = request.POST.get('name') 
        major = request.POST.get('major')
        age = request.POST.get('age')
        grade = request.POST.get('grade')
        gender = request.POST.get('gender')
        print('form name : ',name)            
        # db저장
        Student.objects.create(s_name=name,s_major=major,s_age=age,s_grade=grade,s_gender=gender)
        # qs = Student(s_name=name,s_major=major,s_age=age,s_grade=grade,s_gender=gender)
        # qs.save()
                    
        return HttpResponseRedirect(reverse('index'))    
 
# 학생전체리스트
def stuList(request):
    qs = Student.objects.order_by('s_name')
    count = qs.count()
    # dic타입으로 저장
    context = {'stuList':qs,"stuCount":count}
    # context데이터를 html에 보냄
    return render(request,'stuList.html',context)   

# 학생상세페이지 - 간단url:매개변수만 가능, 파라미터:request.GET.get만 가능
def stuView(request,name,major):
    # name = request.GET.get('name')
    # name변수를 가지고 학생 검색 - 타입 : Student객체
    qs = Student.objects.get(s_name=name)
    context={'stu':qs}
    return render(request,'stuView.html',context)
    






#### stuWrite, stuWriteOk함수를 분리해서 사용

# # 학생 db 등록 - form데이터 전달받음 : name,major,age,grade,gender
# def stuWriteOk(request):
#     # form데이터 - POST
#     name = request.POST.get('name') 
#     major = request.POST.get('major')
#     age = request.POST.get('age')
#     grade = request.POST.get('grade')
#     gender = request.POST.get('gender')
#     print('form name : ',name)            
#     # db저장
#     Student.objects.create(s_name=name,s_major=major,s_age=age,s_grade=grade,s_gender=gender)
#     # qs = Student(s_name=name,s_major=major,s_age=age,s_grade=grade,s_gender=gender)
#     # qs.save()
                
#     return HttpResponseRedirect(reverse('index'))


#######  db 명령어 #######
# # 1. create
# # query = Student(s_name='홍길순',s_major='영문학과',s_age=24,s_grade=4,s_gender='여자')
# # query.save()  

# # 2. read  
# # 전체데이터 읽어오기
# qs = Student.objects.all()
# print(qs)
# # 1개데이터 읽어오기
# qs2 = Student.objects.get(s_name='홍길동')
# print(qs2)
# # 검색
# qs3 = Student.objects.filter(s_name__contains='홍')
# print(qs3)

# # 3. update
# qs4 = Student.objects.get(s_name='홍길동')
# qs4.s_major = '아동학과'
# qs4.save()
# print('변경되었습니다')

# # 4. delete
# # qs5 = Student.objects.get(s_name='홍길자')
# # qs5.delete()
# # print('삭제되었습니다.')

09.django/d0517/stuPjt/students/templates/stuList.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        table,th,td{border:1px solid black; border-collapse:collapse;
        text-align:center; }
        table{width:550px; }
        th{width:200px;}
        
    </style>
</head>
<body>
    <h2>학생전체리스트</h2>
    <h3>학생수 : {{ stuCount }} 명 </h3>
    <table>
        <tr>
            <th>학생이름</th>
            <th>학과</th>
            <th>나이</th>
            <th>학년</th>
            <th>성별</th>
        </tr>
        <!-- context : stuList,count -->
        {% if stuList %}
            {% for stu in stuList %}
            <tr>
                <td><a href="{% url 'students:stuView' stu.s_name stu.s_major %}">{{ stu.s_name }}</a></td>
                <!-- 파이썬 주석 : comment  -->
                {% comment %} <td><a href="/students/stuView?name={{stu.s_name}}">{{ stu.s_name }}</a></td> {% endcomment %}
                <td>{{ stu.s_major }}</td>
                <td>{{ stu.s_age }}</td>
                <td>{{ stu.s_grade }}</td>
                <td>{{ stu.s_gender }}</td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan='5'> 가져올 데이터가 없습니다. </td>
            </tr>
        {% endif %}
    </table>
    <br>
    <a href="{% url 'students:stuWrite' %}"><button>학생등록</button></a>
    <a href="{% url 'index' %}"><button>메인</button></a>
    
</body>
</html>

09.django/d0517/stuPjt/students/templates/stuView.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        table,th,td{border:1px solid black; border-collapse:collapse;
        text-align:center;
        }
        table{width:550px;}
        th{width:200px; height:40px; background:#eee;}
        td{height:30px;}
    </style>
</head>
<body>
    <h2>학생상세페이지</h2>
    <table>
        <tr>
            <th>주제</th>
            <th>내용</th>
        </tr>
        <tr>
            <td>이름</td>
            <td>{{stu.s_name}}</td>
        </tr>
        <tr>
            <td>학과</td>
            <td>{{stu.s_major}}</td>
        </tr>
        <tr>
            <td>나이</td>
            <td>{{stu.s_age}}</td>
        </tr>
        <tr>
            <td>학년</td>
            <td>{{stu.s_grade}}</td>
        </tr>
        <tr>
            <td>성별</td>
            <td>{{stu.s_gender}}</td>
        </tr>
    </table>
    <br>
    <a href="{% url 'students:stuList' %}"><button>목록</button></a>
    <a href="#"><button>수정</button></a>
    <a href="#"><button>삭제</button></a>
    
</body>
</html>

09.django/d0517/stuPjt/students/templates/stuWrite.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        function cancel(){
            if(confirm('등록을 취소하시겠습니까?')){
                location.href="{% url 'students:stuList' %}"
            }
        }
    </script>
</head>
<body>
    <h2>학생등록페이지</h2>
    <form action="{% url 'students:stuWrite' %}" method='post' name='frm'>
        {% csrf_token %}
        <label>학생이름</label>
        <input type='text' name='name'><br>
        <label>학과</label>
        <input type='text' name='major'><br>
        <label>나이</label>
        <input type='text' name='age'><br>
        <label>학년</label>
        <input type='text' name='grade'><br>
        <label>성별</label>
        <input type='radio' name='gender' id='male' value='남자'>
        <label for='male'>남자</label>
        <input type='radio' name='gender' id='female' value='여자'>
        <label for='female'>여자</label>
        <br>

        <input type='submit' value='전송'>
        <button type='button' onclick='cancel()'>취소</button> 
    </form>
    
</body>
</html>