09.django/d0520_boardlogin/comm/comm/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # home연결 - index.html
    path('',include('home.urls')),
    # freeboard app연결
    path('freeboard/',include('freeboard.urls')),
    # member app연결
    path('member/',include('member.urls')),
]

09.django/d0520_boardlogin/comm/freeboard/urls.py
from django.urls import path,include
from . import views

app_name='freeboard'
urlpatterns = [
    # fList.html연결
    path('fList/',views.fList,name='fList'),
    # fView.html연결
    path('<str:f_no>/fView',views.fView,name='fView'),
    # fWrite.html연결
    path('fWrite/',views.fWrite,name='fWrite'),
    # fUpdate.html연결
    path('<str:f_no>/fUpdate',views.fUpdate,name='fUpdate'),
    # fDelete연결
    path('<str:f_no>/fDelete',views.fDelete,name='fDelete'),
]

09.django/d0520_boardlogin/comm/home/urls.py
from django.urls import path,include
from . import views

app_name=''
urlpatterns = [
    path('',views.index,name='index'),
]

09.django/d0520_boardlogin/comm/member/urls.py
from django.urls import include,path
from . import views

app_name='member'
urlpatterns = [
    # login페이지 연결
    path('login/',views.login,name='login'),
    # logout페이지 연결
    path('logout/',views.logout,name='logout'),
]

09.django/d0520_boardlogin/comm/freeboard/models.py
from django.db import models
from datetime import datetime

class Freeboard(models.Model):
    f_no = models.AutoField(primary_key=True)
    id = models.CharField(max_length=100)
    f_title = models.CharField(max_length=1000)
    f_content = models.TextField()
    f_group = models.IntegerField(default=0)
    f_step = models.IntegerField(default=0)
    f_indent = models.IntegerField(default=0)
    f_hit = models.IntegerField(default=1)
    f_createdate =models.DateTimeField(default=datetime.now(),blank=True)
    f_updatedate = models.DateTimeField(default=datetime.now(),blank=True)
    f_file = models.ImageField(blank=True)
    
    def __str__(self):
        return self.f_title
    

09.django/d0520_boardlogin/comm/member/models.py
from datetime import datetime
from django.db import models

class Member(models.Model):
    id = models.CharField(max_length=30,primary_key=True) 
    pw = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    nickname = models.CharField(max_length=100)
    tel = models.CharField(max_length=13)
    zipcode = models.CharField(max_length=6)
    address1 = models.CharField(max_length=300)
    address2 = models.CharField(max_length=300)
    gender = models.CharField(max_length=10)
    hobby = models.CharField(max_length=100)
    createdate = models.DateTimeField(datetime.now(),blank=True)
    updatedate = models.DateTimeField(datetime.now(),blank=True)
    
    def __str__(self):
        return self.id

09.django/d0520_boardlogin/comm/freeboard/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from freeboard.models import Freeboard

# freeboard fDelete 함수
def fDelete(request,f_no):
    qs = Freeboard.objects.get(f_no=f_no)
    qs.delete()
    return redirect('/freeboard/fList')

# freeboard fUpdate페이지 함수
def fUpdate(request,f_no):
    if request.method=='GET':
        qs = Freeboard.objects.get(f_no=f_no)
        context = { 'fboard':qs }
        return render(request,'fUpdate.html',context)
    else:
        qs = Freeboard.objects.get(f_no=f_no)
        qs.f_title = request.POST.get('title')
        qs.f_content = request.POST.get('content')
        qs.save()
        return redirect('/freeboard/fList')


# freeboard fWrite페이지 함수
def fWrite(request):
    if request.method=='GET':
        return render(request,'fWrite.html')
    else:
       # f_no,
       # f_group = f_no와 같아야 함.
       # form request데이터 읽기
       id = request.POST.get('id')
       f_title = request.POST.get('title')
       f_content = request.POST.get('content')
       # db에 데이터 저장
       qs = Freeboard(id=id,f_title=f_title,f_content=f_content)
       qs.save()
       # f_no는 AutoField이기 때문에 insert때 생성, f_group에 넣음.
       qs.f_group = qs.f_no
       qs.save()  
       return redirect('freeboard:fList')      
        

# freeboard fView페이지 함수
def fView(request,f_no):
    # f_no로 1개 데이터 검색
    qs = Freeboard.objects.get(f_no=f_no)
    context={'fboard':qs}
    return render(request,'fview.html',context)

# freeboard fList페이지 함수
def fList(request):
    print("session_id : ",request.session.get("session_id"))
    qs = Freeboard.objects.order_by('-f_no') # f_no로 역순정렬
    context = {'fList':qs}
    return render(request,'fList.html',context)

09.django/d0520_boardlogin/comm/home/views.py
from django.shortcuts import render

# index페이지 연결
def index(request):
    return render(request,'index.html')

09.django/d0520_boardlogin/comm/member/views.py
from django.shortcuts import get_object_or_404, redirect, render
from member.models import Member

# logout페이지 함수
def logout(request):
    request.session.clear()
    return redirect('/')


# login-get,login-post페이지 함수
def login(request):
    if request.method=='GET':
        return render(request,'login.html')
    else:
        # post로 넘어온 데이터 
        id = request.POST.get('id')
        pw = request.POST.get('pw')
        
        # db에서 id,pw로 검색
        try:
            qs = Member.objects.get(id=id,pw=pw)
            request.session['session_id'] = qs.id
            request.session['session_name'] = qs.name
            request.session['session_nickname'] = qs.nickname
            return redirect('/') 
        except Member.DoesNotExist:
            qs = None
            context={'msg':'아이디 또는 패스워드가 일치하지 않습니다. 다시 로그인 바랍니다.'}
            return render(request,'login.html',context)
        
        # 데이터가 있는지 확인
        # if qs:
        #     request.session['session_id'] = qs.id
        #     request.session['session_name'] = qs.name
        #     request.session['session_nickname'] = qs.nickname
        #     return redirect('/')       
        #     # return render(request,'/index.html',{'msg':'로그인 성공'})       
        # else:
        #     context={'msg':'아이디 또는 패스워드가 일치하지 않습니다. 다시 로그인 바랍니다.'}
        #     return render(request,'login.html',context)

09.django/d0520_boardlogin/comm/freeboard/templates/admin_account.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="css/admin_account.css">
</head>

<body>
  <header>
    <div id="header-left">
      LMS <span>ENTERPRISE</span> Type
    </div>
    <div id="header-right">
      <span>관리자 (GMT+9:00) Seoul</span>
      <img src="http://lmsenterprise2019.itmap.co.kr/_admin/image/logout.png" alt="">

      <table>
        <tr>
          <td class="select">
            <img src="http://lmsenterprise2019.itmap.co.kr/_admin/image/KOR.png" alt="">
            <span>한국어</span>
          </td>
          <td class="arrow">
            <div class="separator"></div>
            <span>▼</span>
          </td>
        </tr>
      </table>

      <table>
        <tr>
          <td class="select">
            <span>LMS 매뉴얼</span>
          </td>
          <td class="arrow">
            <div class="separator"></div>
            <span>▼</span>
          </td>
        </tr>
      </table>
    </div>
  </header>

  <nav>
    <ul>
      <li><span class="nav1">&emsp;</span> 회원관리</li>
      <li><span class="nav2">&emsp;</span> 상품관리</li>
      <li><span class="nav3">&emsp;</span> 공지사항</li>
      <li><span class="nav4">&emsp;</span> 이벤트</li>
    </ul>
  </nav>

</body>
</html>

09.django/d0520_boardlogin/comm/freeboard/templates/fList.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/notice_list.css' %}">
</head>
<body>
  <header>
    <ul>
      <li>회원가입</li> <span>|</span>
      <li>로그인</li> <span>|</span>
      <li>고객행복센터</li> <span>|</span>
      <li>배송지역검색</li> <span>|</span>
      <li>기프트카드 등록</li>
    </ul>
  </header>

  <nav>
    <div class="logo"></div>

    <div id="search">
      <div class="search"></div><br>
      <span>메뉴찾기</span>
    </div>

    <div id="cart">
      <div class="cart"></div><br>
      <span>장바구니</span>
    </div>

    <div class="nav-menu">
      <ul>
        <li>COOKIT소개</li>
        <li>COOKIT 메뉴</li>
        <li>리뷰</li>
        <li>이벤트</li>
        <li>MY쿡킷</li>
      </ul>  
    </div>
  </nav>

  <section>
    <h1>NOTICE</h1>
    <div class="wrapper">
      <form action="/search" name="search" method="post">
        <select name="category" id="category">
          <option value="0">전체</option>
          <option value="title">제목</option>
          <option value="content">내용</option>
        </select>

        <div class="title">
          <input type="text" size="16">
        </div>
  
        <button type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>

    <table>
      <colgroup>
        <col width="18%">
        <col width="60%">
        <col width="18%">
      </colgroup>
      <tr>
        <th>No.</th>
        <th>제목</th>
        <th>작성일</th>
      </tr>
      {% if fList %}
        {% for fboard in fList %}
          <tr>
            <td>{{fboard.f_no}}</td>
            <td class="table-title"><a href="{% url 'freeboard:fView' fboard.f_no %}">{{fboard.f_title}}</a></td>
            <td>{{fboard.f_createdate|date:'Y-m-d H:i'}}</td>
          </tr>
        {% endfor %}
      {% else %}
        <tr>
          <td colspan="3">데이터가 없습니다.</td>
        </tr>
      {% endif %}
      
    </table>

    <ul class="page-num">
      <li class="first"></li>
      <li class="prev"></li>
      <li class="num">
        <div>1</div>
      </li>
      <li class="next"></li>
      <li class="last"></li>
    </ul>

    <a href="{% url 'freeboard:fWrite' %}"><div class="write">쓰기</div></a>
  </section>

  <footer>
    <div class="wrapper">
      <div class="footer-left">
        <div class="footer-logo"></div>
        <div class="copyright">© COOKIT ALL RIGHTS RESERVED</div>
      </div>
  
      <div class="footer-center">
        <ul class="footer-nav">
          <li class="first-list">이용약관</li>
          <li class="green">개인정보처리 방침</li>
          <li>법적고지</li>
          <li>사업자정보 확인</li>
        </ul>
  
        <ul class="footer-info">
          <li class="first-list">씨제이제일제당(주)</li>
          <li>대표이사 : 손경식,강신호,신현재</li>
          <li>사업자등록번호 : 104-86-09535</li>
          <li class="first-list">주소 : 서울 중구 동호로 330 CJ제일제당 센터 (우) 04560</li>
          <li>통신판매업신고 중구 제 07767호</li>
          <li class="first-list">개인정보보호책임자 : 조영민</li>
          <li>이메일 : cjon@cj.net</li>
          <li>호스팅제공자 : CJ올리브네트웍스㈜</li>
        </ul>
  
        <div id="check">고객님은 안전거래를 위해 현금등으로 결제시 LG U+ 전자 결제의 매매보호(에스크로) 서비스를 이용하실 수 있습니다. <span class="check">가입 사실 확인</span></div>
      </div>
  
      <div class="footer-right">
        <div id="shortcut">
          <span>CJ그룹계열사 바로가기</span>
          <div class="shortcut"></div>
        </div>
  
        <div class="call">고객행복센터 1668-1920</div>
        <div class="inquery">1:1 문의</div>
      </div>
  
    </div>
  </footer>
</body>
</html>

09.django/d0520_boardlogin/comm/freeboard/templates/fUpdate.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pages - Login</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/write.css' %}">
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script>
  function writeBtn(){
    if ($("#title").val()==""){
      alert('제목을 입력하셔야 등록이 가능합니다.')
      $("#title").focus()
      return false
    }

    $("#write").submit()  
    
  }
</script>
</head>

<body>
  <header>
    <ul>
      <li>회원가입</li> <span>|</span>
      <li>로그인</li> <span>|</span>
      <li>고객행복센터</li> <span>|</span>
      <li>배송지역검색</li> <span>|</span>
      <li>기프트카드 등록</li>
    </ul>
  </header>

  <nav>
    <div class="logo"></div>

    <div id="search">
      <div class="search"></div><br>
      <span>메뉴찾기</span>
    </div>

    <div id="cart">
      <div class="cart"></div><br>
      <span>장바구니</span>
    </div>

    <div class="nav-menu">
      <ul>
        <li>COOKIT소개</li>
        <li>COOKIT 메뉴</li>
        <li>리뷰</li>
        <li>이벤트</li>
        <li>MY쿡킷</li>
      </ul>  
    </div>
  </nav>

  <section>
    <h1>관리자 글쓰기</h1>
    <hr>

    <form action="{% url 'freeboard:fUpdate' fboard.f_no %}" name="write" id="write" method="post">
      {% csrf_token %}
      <input type='hidden' name='f_no' value='{{fboard.f_no}}'>
      <table>
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>분류</th>
          <td>
            <div class="category-wrapper">
              <select name="category" id="category">
                <option value="notice">공지</option>
                <option value="event">이벤트</option>
              </select>  
            </div>
          </td>
        </tr>
        <tr>
          <th>아이디</th>
          <td>
            <input type="text" name="id" value='{{ fboard.id }}' readonly >
          </td>
        </tr>
        <tr>
          <th>제목</th>
          <td>
            <input type="text" name="title" id="title" value='{{fboard.f_title}}'>
          </td>
        </tr>
        <tr>
          <th>내용</th>
          <td>
            <textarea name="content" cols="50" rows="10">{{fboard.f_content}}</textarea>
          </td>
        </tr>
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="file" id="file">
          </td>
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="button" class="write" onclick="writeBtn()">수정완료</button>
        <button type="button" class="cancel" onclick="javascript:location.href='/freeboard/fList'">취소</button>
      </div>
    </form>

  </section>

  <footer>
    <div class="wrapper">
      <div class="footer-left">
        <div class="footer-logo"></div>
        <div class="copyright">© COOKIT ALL RIGHTS RESERVED</div>
      </div>
  
      <div class="footer-center">
        <ul class="footer-nav">
          <li class="first-list">이용약관</li>
          <li class="green">개인정보처리 방침</li>
          <li>법적고지</li>
          <li>사업자정보 확인</li>
        </ul>
  
        <ul class="footer-info">
          <li class="first-list">씨제이제일제당(주)</li>
          <li>대표이사 : 손경식,강신호,신현재</li>
          <li>사업자등록번호 : 104-86-09535</li>
          <li class="first-list">주소 : 서울 중구 동호로 330 CJ제일제당 센터 (우) 04560</li>
          <li>통신판매업신고 중구 제 07767호</li>
          <li class="first-list">개인정보보호책임자 : 조영민</li>
          <li>이메일 : cjon@cj.net</li>
          <li>호스팅제공자 : CJ올리브네트웍스㈜</li>
        </ul>
  
        <div id="check">고객님은 안전거래를 위해 현금등으로 결제시 LG U+ 전자 결제의 매매보호(에스크로) 서비스를 이용하실 수 있습니다. <span class="check">가입 사실 확인</span></div>
      </div>
  
      <div class="footer-right">
        <div id="shortcut">
          <span>CJ그룹계열사 바로가기</span>
          <div class="shortcut"></div>
        </div>
  
        <div class="call">고객행복센터 1668-1920</div>
        <div class="inquery">1:1 문의</div>
      </div>
  
    </div>
  </footer>
</body>
</html>

09.django/d0520_boardlogin/comm/freeboard/templates/fView.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/read.css'%}">
  <script>
    function deleteBtn(){
      if (confirm('정말 삭제하시겠습니까?')){
        location.href="{% url 'freeboard:fDelete' fboard.f_no %}"
      }else{
        return false
      }
    }
  </script>
</head>

<body>
  <header>
    <ul>
      <li>회원가입</li> <span>|</span>
      <li>로그인</li> <span>|</span>
      <li>고객행복센터</li> <span>|</span>
      <li>배송지역검색</li> <span>|</span>
      <li>기프트카드 등록</li>
    </ul>
  </header>

  <nav>
    <div class="logo"></div>

    <div id="search">
      <div class="search"></div><br>
      <span>메뉴찾기</span>
    </div>

    <div id="cart">
      <div class="cart"></div><br>
      <span>장바구니</span>
    </div>

    <div class="nav-menu">
      <ul>
        <li>COOKIT소개</li>
        <li>COOKIT 메뉴</li>
        <li>리뷰</li>
        <li>이벤트</li>
        <li>MY쿡킷</li>
      </ul>  
    </div>
  </nav>

  <section>
    <h1>NOTICE</h1>
   
    <table>
      <tr>
        <th><strong>제&nbsp;&nbsp;&nbsp;목</strong><span class="separator">|</span>{{ fboard.f_title }}</th>
      </tr>
      <tr>
        <td><strong>작성자</strong> <span class="separator">|</span>{{ fboard.id }}</td>
      </tr>
      <tr>
        <td><strong>날&nbsp;&nbsp;&nbsp;짜</strong><span class="separator">|</span>{{ fboard.f_createdate|date:'Y-m-d H:i' }}</td>
      </tr>
      <tr>
        <td class="article">
          <div width="80%">{{ fboard.f_content }}</div>
        </td>
      </tr>
      <tr>
        <td><strong>다음글</strong> <span class="separator">|</span> [키즈잼] 2월 프로그램 안내</td>
      </tr>
      <tr>
        <td><strong>이전글</strong> <span class="separator">|</span> [키즈잼] 2020년 1분기 정기 휴관일 안내</td>
      </tr>
    </table>

    <a href="{% url 'freeboard:fList' %}"><div class="list btn">목록</div></a>
    <div class="list btn" onclick="deleteBtn()">삭제</div>
    <a href="{% url 'freeboard:fUpdate' fboard.f_no  %}"><div class="list btn">수정</div></a>
  </section>

  <footer>
    <div class="wrapper">
      <div class="footer-left">
        <div class="footer-logo"></div>
        <div class="copyright">© COOKIT ALL RIGHTS RESERVED</div>
      </div>
  
      <div class="footer-center">
        <ul class="footer-nav">
          <li class="first-list">이용약관</li>
          <li class="green">개인정보처리 방침</li>
          <li>법적고지</li>
          <li>사업자정보 확인</li>
        </ul>
  
        <ul class="footer-info">
          <li class="first-list">씨제이제일제당(주)</li>
          <li>대표이사 : 손경식,강신호,신현재</li>
          <li>사업자등록번호 : 104-86-09535</li>
          <li class="first-list">주소 : 서울 중구 동호로 330 CJ제일제당 센터 (우) 04560</li>
          <li>통신판매업신고 중구 제 07767호</li>
          <li class="first-list">개인정보보호책임자 : 조영민</li>
          <li>이메일 : cjon@cj.net</li>
          <li>호스팅제공자 : CJ올리브네트웍스㈜</li>
        </ul>
  
        <div id="check">고객님은 안전거래를 위해 현금등으로 결제시 LG U+ 전자 결제의 매매보호(에스크로) 서비스를 이용하실 수 있습니다. <span class="check">가입 사실 확인</span></div>
      </div>
  
      <div class="footer-right">
        <div id="shortcut">
          <span>CJ그룹계열사 바로가기</span>
          <div class="shortcut"></div>
        </div>
  
        <div class="call">고객행복센터 1668-1920</div>
        <div class="inquery">1:1 문의</div>
      </div>
  
    </div>
  </footer>
</body>
</html>

09.django/d0520_boardlogin/comm/freeboard/templates/fwrite.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pages - Login</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/write.css' %}">
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script>
  function writeBtn(){
    if ($("#title").val()==""){
      alert('제목을 입력하셔야 등록이 가능합니다.')
      $("#title").focus()
      return false
    }

    $("#write").submit()  
    
  }
</script>
</head>

<body>
  <header>
    <ul>
      <li>회원가입</li> <span>|</span>
      <li>로그인</li> <span>|</span>
      <li>고객행복센터</li> <span>|</span>
      <li>배송지역검색</li> <span>|</span>
      <li>기프트카드 등록</li>
    </ul>
  </header>

  <nav>
    <div class="logo"></div>

    <div id="search">
      <div class="search"></div><br>
      <span>메뉴찾기</span>
    </div>

    <div id="cart">
      <div class="cart"></div><br>
      <span>장바구니</span>
    </div>

    <div class="nav-menu">
      <ul>
        <li>COOKIT소개</li>
        <li>COOKIT 메뉴</li>
        <li>리뷰</li>
        <li>이벤트</li>
        <li>MY쿡킷</li>
      </ul>  
    </div>
  </nav>

  <section>
    <h1>관리자 글쓰기</h1>
    <hr>

    <form action="{% url 'freeboard:fWrite' %}" name="write" id="write" method="post">
      {% csrf_token %}
      <table>
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>분류</th>
          <td>
            <div class="category-wrapper">
              <select name="category" id="category">
                <option value="notice">공지</option>
                <option value="event">이벤트</option>
              </select>  
            </div>
          </td>
        </tr>
        <tr>
          <th>아이디</th>
          <td>
            <input type="text" name="id" value={{request.session.session_id}} readonly >
          </td>
        </tr>
        <tr>
          <th>제목</th>
          <td>
            <input type="text" name="title" id="title">
          </td>
        </tr>
        <tr>
          <th>내용</th>
          <td>
            <textarea name="content" cols="50" rows="10"></textarea>
          </td>
        </tr>
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="file" id="file">
          </td>
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="button" class="write" onclick="writeBtn()">작성완료</button>
        <button type="button" class="cancel" onclick="javascript:location.href='/freeboard/fList'">취소</button>
      </div>
    </form>

  </section>

  <footer>
    <div class="wrapper">
      <div class="footer-left">
        <div class="footer-logo"></div>
        <div class="copyright">© COOKIT ALL RIGHTS RESERVED</div>
      </div>
  
      <div class="footer-center">
        <ul class="footer-nav">
          <li class="first-list">이용약관</li>
          <li class="green">개인정보처리 방침</li>
          <li>법적고지</li>
          <li>사업자정보 확인</li>
        </ul>
  
        <ul class="footer-info">
          <li class="first-list">씨제이제일제당(주)</li>
          <li>대표이사 : 손경식,강신호,신현재</li>
          <li>사업자등록번호 : 104-86-09535</li>
          <li class="first-list">주소 : 서울 중구 동호로 330 CJ제일제당 센터 (우) 04560</li>
          <li>통신판매업신고 중구 제 07767호</li>
          <li class="first-list">개인정보보호책임자 : 조영민</li>
          <li>이메일 : cjon@cj.net</li>
          <li>호스팅제공자 : CJ올리브네트웍스㈜</li>
        </ul>
  
        <div id="check">고객님은 안전거래를 위해 현금등으로 결제시 LG U+ 전자 결제의 매매보호(에스크로) 서비스를 이용하실 수 있습니다. <span class="check">가입 사실 확인</span></div>
      </div>
  
      <div class="footer-right">
        <div id="shortcut">
          <span>CJ그룹계열사 바로가기</span>
          <div class="shortcut"></div>
        </div>
  
        <div class="call">고객행복센터 1668-1920</div>
        <div class="inquery">1:1 문의</div>
      </div>
  
    </div>
  </footer>
</body>
</html>

09.django/d0520_boardlogin/comm/home/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if msg %}
    <script>alert('{{ kwargs.msg }}')</script>
    {% endif %}
    <h2>메인페이지</h2>
    <ul>
        {% if not request.session.session_id %}
        <li><h2>로그인을 하셔야 글쓰기가 가능합니다.</h2></li>
        <a href="{% url 'member:login' %}"><li>로그인</li></a>
        <li>회원가입</li>
        <li>-------</li>
        {% else %}
        <li>{{ request.session.session_nickname }} 님 환영합니다.</li>
        <a href="{% url 'member:logout' %}"><li>로그아웃</li></a>
        <a href="{% url 'freeboard:fList' %}"><li>자유게시판</li></a>
        <a href="#"><li>전체회원리스트</li></a>
        <a href="/admin"><li>admin</li></a>
        {% endif %}
    </ul>
</body>
</html>