09.django/d0523_02/sproject/fboard/urls.py
from django.urls import include,path
from . import views

app_name='fboard'
urlpatterns = [
    path('<int:nowpage>/fList/',views.fList,name='fList'),
    path('<int:nowpage>/fWrite/',views.fWrite,name='fWrite'),
    path('<int:nowpage>/<str:f_no>/fView',views.fView,name='fView'),
    # 답글쓰기
    path('<int:nowpage>/<str:f_no>/fReply',views.fReply,name='fReply'),
    # 삭제
    path('<int:nowpage>/<str:f_no>/fDelete',views.fDelete,name='fDelete'),
    # 수정
    path('<int:nowpage>/<str:f_no>/fUpdate',views.fUpdate,name='fUpdate'),
]

09.django/d0523_02/sproject/fboard/models.py
from datetime import datetime
from django.db import models
from member.models import Member

class Fboard(models.Model):
    f_no = models.AutoField(primary_key=True)
    # primary key:Member객체, id 1개 컬럼으로 받는데, ForeignKey:Member객체
    member = models.ForeignKey(Member,on_delete=models.DO_NOTHING,null=True)
    # id = models.CharField(max_length=100)
    f_title = models.CharField(max_length=1000)
    f_content = models.TextField()
    f_group = models.IntegerField(default=0)
    f_step = models.IntegerField(default=0)
    f_indent = models.IntegerField(default=0)
    f_hit = models.IntegerField(default=1)
    f_createdate =models.DateTimeField(default=datetime.now(),blank=True)
    f_updatedate = models.DateTimeField(default=datetime.now(),blank=True)
    f_file = models.ImageField(blank=True)
    f_file2 = models.ImageField(blank=True)
    
    def __str__(self):
        return self.f_title

09.django/d0523_02/sproject/fboard/views.py
from django.shortcuts import redirect, render
from fboard.models import Fboard
from member.models import Member
from django.db.models import F 
from django.core.paginator import Paginator

# 게시판 수정 함수
def fUpdate(request,nowpage,f_no):
    if request.method == 'GET':
        qs = Fboard.objects.get(f_no=f_no)
        context = {'board':qs,'nowpage':nowpage}
        return render(request,'fUpdate.html',context)
    else:
        # 수정form에서 데이터 전달
        id = request.POST.get('id')
        title = request.POST.get('title')
        content = request.POST.get('content')
        file = request.FILES.get('file',None)
        print("file : ",file)
        # db에 수정저장
        qs = Fboard.objects.get(f_no=f_no)
        qs.f_title = title
        qs.f_content = content
        if file:  # file등록이 되었으면 저장함.
            qs.f_file = file
            print("qs.f_file ok")
        
           
        qs.save()
        return redirect('fboard:fList',nowpage)

# 게시판 삭제 함수
def fDelete(request,nowpage,f_no):
    qs = Fboard.objects.get(f_no=f_no)
    qs.delete()
    return redirect('fboard:fList',nowpage)

# 게시판 답글쓰기 함수
def fReply(request,nowpage,f_no):
    if request.method == 'GET':
        qs = Fboard.objects.get(f_no=f_no) 
        context={'board':qs,'nowpage':nowpage}
        return render(request,'fReply.html',context)
    else:
        # id = request.session.session_id
        id = request.POST.get('id')
        print("id:",id)
        member = Member.objects.get(id=id)
        # request 넘어온 데이터타입 : str타입
        group = int(request.POST.get('group'))
        step = int(request.POST.get('step'))
        indent = int(request.POST.get('indent'))
        
        title = request.POST.get('title')
        content = request.POST.get('content')
        file = request.FILES.get('file',None)
        # file = request.POST.get('file',None)
        
        # 부모group에서 부모보다 큰 step 1씩증가, gt보다 큰수
        # reboard = Fboard.objects.filter(f_group=group,f_step_gt=step)
        # # F참조객체: db에서 검색을 해서 가져올수 있음.
        # reboard.update(f_step=F('f_step')+1)
        
        # 부모group에서 부모보다 큰 step 1씩증가, gt보다 큰수
        # F참조객체: db에서 검색을 해서 가져올수 있음.
        Fboard.objects.filter(f_group=group,f_step__gt=step).update(f_step=F('f_step')+1)
        
        # step: 출력순서, indent: 들여쓰기
        qs=Fboard(member=member,f_title=title,f_content=content,f_group=group\
            ,f_step=step+1,f_indent=indent+1,f_file=file)
        qs.save() # f_no
        
        return redirect('fboard:fList',nowpage)
    

# 게시판 읽기 함수
def fView(request,nowpage,f_no):
    qs = Fboard.objects.get(f_no=f_no)
    try:
        qs_prev = Fboard.objects.filter(f_group=qs.f_group,f_step__lt=qs.f_step).order_by('-f_group','f_step').first().f_no
        print("1")
    except:
        try:
            qs_prev = Fboard.objects.filter(f_group__gt=qs.f_group).order_by('-f_group','f_step').last().f_no
        except:
            qs_prev = Fboard.objects.order_by('-f_group','f_step').first().f_no    
        print("1_2")
    print("이전글 f_no : ",qs_prev)
    try:
       qs_next = Fboard.objects.filter(f_group=qs.f_group,f_step__gt=qs.f_step).order_by('-f_group','f_step').last().f_no
       print("2")
    except:
       try:
           qs_next = Fboard.objects.filter(f_group__lt=qs.f_group).order_by('-f_group','f_step').first().f_no
       except:
           qs_next = Fboard.objects.order_by('-f_group','f_step').last().f_no  
       print("2_2")
    print("다음글 f_no : ",qs_next)
    qs.f_hit += 1
    qs.save()
    qsPrev = Fboard.objects.get(f_no=qs_prev)
    qsNext = Fboard.objects.get(f_no=qs_next)
    context={'board':qs,'board_prev':qsPrev,'board_next':qsNext,'nowpage':nowpage}
    return render(request,'fView.html',context)

# 게시판 글쓰기 함수
def fWrite(request,nowpage):
    if request.method == 'GET':
        context={"nowpage":nowpage}
        return render(request,'fWrite.html',context)
    else:
        # form넘어온 데이터
        id = request.POST.get("id")
        member = Member.objects.get(id=id)
        title = request.POST.get("title")
        content = request.POST.get("content")
        file = request.FILES.get('file',None)
        file2 = request.FILES.get('file2',None)
        # db 저장
        qs = Fboard(member=member,f_title=title,f_content=content,f_file=file,f_file2=file2)
        qs.save()
        qs.f_group = qs.f_no
        qs.save()
        return redirect('fboard:fList',nowpage)
        
        

# 게시판 리스트 함수
def fList(request,nowpage):
    qs = Fboard.objects.order_by('-f_group','f_step')
    # 페이징 처리 - request:str타입
    # page = int(request.GET.get('nowpage',1)) # page변수 전달, 없으면 1
    print("nowpage : ",nowpage)
    paginator = Paginator(qs,10)     # 1페이지 나타낼수 있는 게시글 수 설정.  
    fList = paginator.get_page(nowpage) # 요청한 페이지의 게시글 10개를 전달
    context={'fList':fList,'nowpage':nowpage}
    return render(request,'fList.html',context)

09.django/d0523_02/sproject/fboard/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/notice_list.css' %}">
  <link rel="stylesheet" href="{% static 'css/read.css' %}">
  <script>
    function writeBtn(){
      location.href="{% url 'fboard:fWrite' nowpage %}"
    }
  </script>
</head>
<body>
  <header>
    <ul>
      <li>회원가입</li> <span>|</span>
      <li>로그인</li> <span>|</span>
      <li>고객행복센터</li> <span>|</span>
      <li>배송지역검색</li> <span>|</span>
      <li><a href="/admin">admin</a></li>
    </ul>
  </header>

  <nav>
    <a href="{% url 'index' %}"><div class="logo"></div></a>
    <div id="search">
      <div class="search"></div><br>
      <span>메뉴찾기</span>
    </div>

    <div id="cart">
      <div class="cart"></div><br>
      <span>장바구니</span>
    </div>

    <div class="nav-menu">
      <ul>
        <li>COOKIT소개</li>
        <li>COOKIT 메뉴</li>
        <li>리뷰</li>
        <li>이벤트</li>
        <li>MY쿡킷</li>
      </ul>  
    </div>
  </nav>
  <!-- 내용부분 -->
  <section>
    {% block content-block  %}
    {% endblock content-block  %}
  </section>
  <!-- 내용 부분 끝 -->
  <footer>
    <div class="wrapper">
      <div class="footer-left">
        <div class="footer-logo"></div>
        <div class="copyright">© COOKIT ALL RIGHTS RESERVED</div>
      </div>
  
      <div class="footer-center">
        <ul class="footer-nav">
          <li class="first-list">이용약관</li>
          <li class="green">개인정보처리 방침</li>
          <li>법적고지</li>
          <li>사업자정보 확인</li>
        </ul>
  
        <ul class="footer-info">
          <li class="first-list">씨제이제일제당(주)</li>
          <li>대표이사 : 손경식,강신호,신현재</li>
          <li>사업자등록번호 : 104-86-09535</li>
          <li class="first-list">주소 : 서울 중구 동호로 330 CJ제일제당 센터 (우) 04560</li>
          <li>통신판매업신고 중구 제 07767호</li>
          <li class="first-list">개인정보보호책임자 : 조영민</li>
          <li>이메일 : cjon@cj.net</li>
          <li>호스팅제공자 : CJ올리브네트웍스㈜</li>
        </ul>
  
        <div id="check">고객님은 안전거래를 위해 현금등으로 결제시 LG U+ 전자 결제의 매매보호(에스크로) 서비스를 이용하실 수 있습니다. <span class="check">가입 사실 확인</span></div>
      </div>
  
      <div class="footer-right">
        <div id="shortcut">
          <span>CJ그룹계열사 바로가기</span>
          <div class="shortcut"></div>
        </div>
  
        <div class="call">고객행복센터 1668-1920</div>
        <div class="inquery">1:1 문의</div>
      </div>
  
    </div>
  </footer>
</body>
</html>

09.django/d0523_02/sproject/fboard/templates/fList copy.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/notice_list.css' %}">
  <script>
    function writeBtn(){
      location.href="{% url 'fboard:fWrite' nowpage %}"
    }
  </script>
</head>
<body>
  <header>
    <ul>
      <li>회원가입</li> <span>|</span>
      <li>로그인</li> <span>|</span>
      <li>고객행복센터</li> <span>|</span>
      <li>배송지역검색</li> <span>|</span>
      <li><a href="/admin">admin</a></li>
    </ul>
  </header>

  <nav>
    <a href="{% url 'index' %}"><div class="logo"></div></a>
    <div id="search">
      <div class="search"></div><br>
      <span>메뉴찾기</span>
    </div>

    <div id="cart">
      <div class="cart"></div><br>
      <span>장바구니</span>
    </div>

    <div class="nav-menu">
      <ul>
        <li>COOKIT소개</li>
        <li>COOKIT 메뉴</li>
        <li>리뷰</li>
        <li>이벤트</li>
        <li>MY쿡킷</li>
      </ul>  
    </div>
  </nav>

  <section>
    <h1>NOTICE</h1>
    <div class="wrapper">
      <form action="/search" name="search" method="post">
        {% csrf_token %}
        <select name="category" id="category">
          <option value="0">전체</option>
          <option value="title">제목</option>
          <option value="content">내용</option>
        </select>

        <div class="title">
          <input type="text" size="16">
        </div>
        <button type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>

    <table>
      <colgroup>
        <col width="15%">
        <col width="40%">
        <col width="15%">
        <col width="15%">
        <col width="15%">
      </colgroup>
      <tr>
        <th>No.</th>
        <th>제목</th>
        <th>작성자</th>
        <th>작성일</th>
        <th>조회수</th>
      </tr>
      {% comment %} <tr>
        <td><span class="table-notice">NOTICE</span></td>
        <td class="table-title">신종코로나바이러스 예방관련 운영 안내</td>
        <td>2020-02-28</td>
      </tr> {% endcomment %}
      {% if fList %}
        {% for board in fList %}
        <tr>
          <td>{{board.f_no}}</td>
          <td class="table-title">
            <a href="{% url 'fboard:fView' nowpage board.f_no %}">
              {% if board.f_indent > 0 %}
              {% comment %} board.f_indent 글자로 인식 {% endcomment %}
              {% comment %} "x"|공백제거후 board.f_indent 만큼 리스트 처리 {% endcomment %}
                {% for i in "x"|rjust:board.f_indent %}
                  ▶
                {% endfor %}  
              {% endif %}
              {{board.f_title}}
              {% if board.f_file %}
              <img src="/static/images/dicon1.png">
              {% endif %}
            </a>
          </td>
          <td>{{board.member.name}}</td>
          <td>{{board.f_updatedate|date:'Y-m-d H:i'}}</td>
          <td>{{board.f_hit}}</td>
        </tr>
        {% endfor %}
      {% else %}
        <tr>
          <td colspan='5'>데이터가 없습니다.</td>
        </tr>
      {% endif %}
    </table>
    <!-- 페이징 처리 -->
    <!-- 이전페이지 처리 -->
    <ul class="page-num">
      {% if fList.has_previous %}
        <a href="{% url 'fboard:fList' nowpage=1  %}"><li class="first"></li></a>
        <a href="{% url 'fboard:fList' nowpage=fList.previous_page_number %}"><li class="prev"></li></a>
      {%else%}
        <li class="first"></li>
        <li class="prev"></li>
      {%endif%}
      <!-- 페이지순서 처리 -->
      {% for page in fList.paginator.page_range %}
        {% if page != nowpage %}
          <a href="{% url 'fboard:fList' nowpage=page  %}">
            <li class="num"><div>{{page}}</div></li>
          </a>
        {% else %}
          <li class="num on"><div>{{page}}</div></li>
        {% endif %}
      {% endfor %}  
      
      <!-- 다음페이지 처리 -->
      {% if fList.has_next %}
        <a href="{% url 'fboard:fList' nowpage=fList.next_page_number %}"><li class="next"></li></a>
        <a href="{% url 'fboard:fList' nowpage=fList.paginator.num_pages %}"><li class="last"></li></a>
        {% else %}
        <li class="next"></li>
        <li class="last"></li>
      {% endif %}
    
    </ul>

    <div class="write" onclick="writeBtn()">쓰기</div>
  </section>

  <footer>
    <div class="wrapper">
      <div class="footer-left">
        <div class="footer-logo"></div>
        <div class="copyright">© COOKIT ALL RIGHTS RESERVED</div>
      </div>
  
      <div class="footer-center">
        <ul class="footer-nav">
          <li class="first-list">이용약관</li>
          <li class="green">개인정보처리 방침</li>
          <li>법적고지</li>
          <li>사업자정보 확인</li>
        </ul>
  
        <ul class="footer-info">
          <li class="first-list">씨제이제일제당(주)</li>
          <li>대표이사 : 손경식,강신호,신현재</li>
          <li>사업자등록번호 : 104-86-09535</li>
          <li class="first-list">주소 : 서울 중구 동호로 330 CJ제일제당 센터 (우) 04560</li>
          <li>통신판매업신고 중구 제 07767호</li>
          <li class="first-list">개인정보보호책임자 : 조영민</li>
          <li>이메일 : cjon@cj.net</li>
          <li>호스팅제공자 : CJ올리브네트웍스㈜</li>
        </ul>
  
        <div id="check">고객님은 안전거래를 위해 현금등으로 결제시 LG U+ 전자 결제의 매매보호(에스크로) 서비스를 이용하실 수 있습니다. <span class="check">가입 사실 확인</span></div>
      </div>
  
      <div class="footer-right">
        <div id="shortcut">
          <span>CJ그룹계열사 바로가기</span>
          <div class="shortcut"></div>
        </div>
  
        <div class="call">고객행복센터 1668-1920</div>
        <div class="inquery">1:1 문의</div>
      </div>
  
    </div>
  </footer>
</body>
</html>

09.django/d0523_02/sproject/fboard/templates/fList.html
{% extends 'base.html' %}
{% load static %}

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/notice_list.css' %}">
  <script>
    function writeBtn(){
      location.href="{% url 'fboard:fWrite' nowpage %}"
    }
  </script>
  
    {% block content-block  %}
    <h1>NOTICE</h1>
    <div class="wrapper">
      <form action="/search" name="search" method="post">
        {% csrf_token %}
        <select name="category" id="category">
          <option value="0">전체</option>
          <option value="title">제목</option>
          <option value="content">내용</option>
        </select>

        <div class="title">
          <input type="text" size="16">
        </div>
        <button type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>

    <table>
      <colgroup>
        <col width="15%">
        <col width="40%">
        <col width="15%">
        <col width="15%">
        <col width="15%">
      </colgroup>
      <tr>
        <th>No.</th>
        <th>제목</th>
        <th>작성자</th>
        <th>작성일</th>
        <th>조회수</th>
      </tr>
      {% comment %} <tr>
        <td><span class="table-notice">NOTICE</span></td>
        <td class="table-title">신종코로나바이러스 예방관련 운영 안내</td>
        <td>2020-02-28</td>
      </tr> {% endcomment %}
      {% if fList %}
        {% for board in fList %}
        <tr>
          <td>{{board.f_no}}</td>
          <td class="table-title">
            <a href="{% url 'fboard:fView' nowpage board.f_no %}">
              {% if board.f_indent > 0 %}
              {% comment %} board.f_indent 글자로 인식 {% endcomment %}
              {% comment %} "x"|공백제거후 board.f_indent 만큼 리스트 처리 {% endcomment %}
                {% for i in "x"|rjust:board.f_indent %}
                  ▶
                {% endfor %}  
              {% endif %}
              {{board.f_title}}
              {% if board.f_file %}
              <img src="/static/images/dicon1.png">
              {% endif %}
            </a>
          </td>
          <td>{{board.member.name}}</td>
          <td>{{board.f_updatedate|date:'Y-m-d H:i'}}</td>
          <td>{{board.f_hit}}</td>
        </tr>
        {% endfor %}
      {% else %}
        <tr>
          <td colspan='5'>데이터가 없습니다.</td>
        </tr>
      {% endif %}
    </table>
    <!-- 페이징 처리 -->
    <!-- 이전페이지 처리 -->
    <ul class="page-num">
      {% if fList.has_previous %}
        <a href="{% url 'fboard:fList' nowpage=1  %}"><li class="first"></li></a>
        <a href="{% url 'fboard:fList' nowpage=fList.previous_page_number %}"><li class="prev"></li></a>
      {%else%}
        <li class="first"></li>
        <li class="prev"></li>
      {%endif%}
      <!-- 페이지순서 처리 -->
      {% for page in fList.paginator.page_range %}
        {% if page != nowpage %}
          <a href="{% url 'fboard:fList' nowpage=page  %}">
            <li class="num"><div>{{page}}</div></li>
          </a>
        {% else %}
          <li class="num on"><div>{{page}}</div></li>
        {% endif %}
      {% endfor %}  
      
      <!-- 다음페이지 처리 -->
      {% if fList.has_next %}
        <a href="{% url 'fboard:fList' nowpage=fList.next_page_number %}"><li class="next"></li></a>
        <a href="{% url 'fboard:fList' nowpage=fList.paginator.num_pages %}"><li class="last"></li></a>
        {% else %}
        <li class="next"></li>
        <li class="last"></li>
      {% endif %}
    
    </ul>

    <div class="write" onclick="writeBtn()">쓰기</div>
    {% endblock content-block  %}

09.django/d0523_02/sproject/fboard/templates/fView copy.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/read.css' %}">
  <script>
    function deleteBtn(){
      if(confirm("데이터를 삭제하시겠습니까?")){
        location.href="{% url 'fboard:fDelete' nowpage board.f_no %}"
      }else{
        return false
      }
    }
  </script>
</head>

<body>
  <header>
    <ul>
      <li>회원가입</li> <span>|</span>
      <li>로그인</li> <span>|</span>
      <li>고객행복센터</li> <span>|</span>
      <li>배송지역검색</li> <span>|</span>
      <li><a href="/admin">admin</a></li>
    </ul>
  </header>

  <nav>
    <a href="{% url 'index' %}"><div class="logo"></div></a>

    <div id="search">
      <div class="search"></div><br>
      <span>메뉴찾기</span>
    </div>

    <div id="cart">
      <div class="cart"></div><br>
      <span>장바구니</span>
    </div>

    <div class="nav-menu">
      <ul>
        <li>COOKIT소개</li>
        <li>COOKIT 메뉴</li>
        <li>리뷰</li>
        <li>이벤트</li>
        <li>MY쿡킷</li>
      </ul>  
    </div>
  </nav>

  <section>
    <h1>NOTICE</h1>

    <table>
      <tr>
        <th>{{board.f_title}}</th>
      </tr>
      <tr>
        <td>{{board.member.name}}</td>
      </tr>
      <tr>
        <td>{{board.f_updatedate|date:'Y-m-d H:i'}}</td>
      </tr>
      <tr>
        <td>{{board.f_content}}</td>
      </tr>
      <tr>
        <td>파일이름 |{{board.f_file}}</td>
      </tr>
      <tr>
        <td>
          {% if board.f_file %}
          <img src="{{board.f_file.url}}">
          {% else %}
          <h4>이미지 없음</h4>
          {% endif %}
        </td>
      </tr>
      <tr>
        <td>
          {% if board.f_file2 %}
          <img src="{{board.f_file2.url}}">
          {% else %}
          <h4>이미지 없음</h4>
          {% endif %}
        </td>
      </tr>
      <tr>
        <td><strong>다음글</strong> <span class="separator">|</span> {{board_prev.f_title}}</td>
      </tr>
      <tr>
        <td><strong>이전글</strong> <span class="separator">|</span> {{board_next.f_title}}</td>
      </tr>
    </table>

    <a href="{% url 'fboard:fList' nowpage %}"><div class="list">목록</div></a>
    <div class="list"><a href="{% url 'fboard:fReply' nowpage board.f_no %}">답글</a></div>
    <div class="list" onclick="deleteBtn()">삭제</div>
    <div class="list"><a href="{% url 'fboard:fUpdate' nowpage board.f_no %}">수정</a></div>
  </section>

  <footer>
    <div class="wrapper">
      <div class="footer-left">
        <div class="footer-logo"></div>
        <div class="copyright">© COOKIT ALL RIGHTS RESERVED</div>
      </div>
  
      <div class="footer-center">
        <ul class="footer-nav">
          <li class="first-list">이용약관</li>
          <li class="green">개인정보처리 방침</li>
          <li>법적고지</li>
          <li>사업자정보 확인</li>
        </ul>
  
        <ul class="footer-info">
          <li class="first-list">씨제이제일제당(주)</li>
          <li>대표이사 : 손경식,강신호,신현재</li>
          <li>사업자등록번호 : 104-86-09535</li>
          <li class="first-list">주소 : 서울 중구 동호로 330 CJ제일제당 센터 (우) 04560</li>
          <li>통신판매업신고 중구 제 07767호</li>
          <li class="first-list">개인정보보호책임자 : 조영민</li>
          <li>이메일 : cjon@cj.net</li>
          <li>호스팅제공자 : CJ올리브네트웍스㈜</li>
        </ul>
  
        <div id="check">고객님은 안전거래를 위해 현금등으로 결제시 LG U+ 전자 결제의 매매보호(에스크로) 서비스를 이용하실 수 있습니다. <span class="check">가입 사실 확인</span></div>
      </div>
  
      <div class="footer-right">
        <div id="shortcut">
          <span>CJ그룹계열사 바로가기</span>
          <div class="shortcut"></div>
        </div>
  
        <div class="call">고객행복센터 1668-1920</div>
        <div class="inquery">1:1 문의</div>
      </div>
  
    </div>
  </footer>
</body>
</html>

09.django/d0523_02/sproject/fboard/templates/fView.html
{% extends 'base.html' %}
{% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/read.css' %}">
  <script>
    function deleteBtn(){
      if(confirm("데이터를 삭제하시겠습니까?")){
        location.href="{% url 'fboard:fDelete' nowpage board.f_no %}"
      }else{
        return false
      }
    }
  </script>
  {% block content-block  %}
    <h1>NOTICE</h1>

    <table>
      <tr>
        <th>{{board.f_title}}</th>
      </tr>
      <tr>
        <td>{{board.member.name}}</td>
      </tr>
      <tr>
        <td>{{board.f_updatedate|date:'Y-m-d H:i'}}</td>
      </tr>
      <tr>
        <td>{{board.f_content}}</td>
      </tr>
      <tr>
        <td>파일이름 |{{board.f_file}}</td>
      </tr>
      <tr>
        <td>
          {% if board.f_file %}
          <img src="{{board.f_file.url}}">
          {% else %}
          <h4>이미지 없음</h4>
          {% endif %}
        </td>
      </tr>
      <tr>
        <td>
          {% if board.f_file2 %}
          <img src="{{board.f_file2.url}}">
          {% else %}
          <h4>이미지 없음</h4>
          {% endif %}
        </td>
      </tr>
      <tr>
        <td><strong>다음글</strong> <span class="separator">|</span> {{board_prev.f_title}}</td>
      </tr>
      <tr>
        <td><strong>이전글</strong> <span class="separator">|</span> {{board_next.f_title}}</td>
      </tr>
    </table>

    <a href="{% url 'fboard:fList' nowpage %}"><div class="list">목록</div></a>
    <div class="list"><a href="{% url 'fboard:fReply' nowpage board.f_no %}">답글</a></div>
    <div class="list" onclick="deleteBtn()">삭제</div>
    <div class="list"><a href="{% url 'fboard:fUpdate' nowpage board.f_no %}">수정</a></div>
    {% endblock content-block  %}